[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --alluredir=allure-results
    --strict-markers
markers =
    smoke: быстрая проверка основных функций
    regression: полное регрессионное тестирование
    negative: негативные сценарии
    performance: проверки производительности